[tool.poetry]
name = "langchain-googledrive"
version = "0.1"
description = "This is a temporary project while I wait for my langchain [pull-request](https://github.com/hwchase17/langchain/pull/5135) to be validated."
authors = ["Philippe PRADOS"]
license = "MIT License"
readme = "README.md"
repository = "https://www.github.com/pprados/langchain-googledrive"
packages = [{include = "langchain_googledrive"}]

[tool.poetry.dependencies]
python = "^3.8"
langchain = "*"
